//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDemo
    {
        public int ID { get; set; }
        public string uName { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
    }
}
